"""Create links table in new db imported

Revision ID: 3e7c44ea2488
Revises: 4d9224ed17d2
Create Date: 2024-08-13 01:30:10.653154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3e7c44ea2488'
down_revision: Union[str, None] = '4d9224ed17d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###