"""dropped users table

Revision ID: 446730970494
Revises: ac1182785ba2
Create Date: 2024-08-18 18:31:23.980772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '446730970494'
down_revision: Union[str, None] = 'ac1182785ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profile_picture', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auth_type', sa.Enum('crypto', 'supabase', name='auth_type_enum'), nullable=True),
    sa.Column('supabase_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decentralized_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stx_address_testnet', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stx_address_mainnet', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('btc_address_mainnet', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('btc_address_testnet', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wallet_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('public_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gaia_hub_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_foreign_key(None, 'links', 'users', ['user_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###