"""added user_id to Link Table 2

Revision ID: 5c1fc76d5b92
Revises: 5bcd42f3ccc6
Create Date: 2024-08-13 17:37:19.318851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c1fc76d5b92'
down_revision: Union[str, None] = '5bcd42f3ccc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_links_uuid', table_name='links')
    op.drop_table('links')
    op.drop_index('ix_users_uuid', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('auth_type', postgresql.ENUM('crypto', 'supabase', name='auth_type_enum'), autoincrement=False, nullable=True),
    sa.Column('supabase_user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('decentralized_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stx_address_testnet', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stx_address_mainnet', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('btc_address_mainnet', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('btc_address_testnet', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wallet_provider', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('public_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gaia_hub_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uuid', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_uuid', 'users', ['uuid'], unique=True)
    op.create_table('links',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], name='links_user_id_fkey'),
    sa.PrimaryKeyConstraint('uuid', name='links_pkey')
    )
    op.create_index('ix_links_uuid', 'links', ['uuid'], unique=True)
    # ### end Alembic commands ###