"""bio

Revision ID: 8f57bf51b253
Revises: c26bf24cb83c
Create Date: 2024-09-05 10:26:45.316319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8f57bf51b253'
down_revision: Union[str, None] = 'c26bf24cb83c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('links_user_id_fkey', 'links', type_='foreignkey')
    op.create_foreign_key(None, 'links', 'users', ['user_id'], ['uuid'])
    op.add_column('users', sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.create_foreign_key('links_user_id_fkey', 'links', 'users', ['user_id'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###