"""transactions

Revision ID: 9b90b4aa7f33
Revises: 3b78dffbe304
Create Date: 2024-09-11 13:06:55.846490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9b90b4aa7f33'
down_revision: Union[str, None] = '3b78dffbe304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'platform',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'platform',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###